apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling
  template:
    metadata:
      labels:
        app: autoscaling
    spec:
      containers:
      - name: autoscaling
        image: testapp/webapp
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "10Mi"  # Запрос памяти
          limits:
            memory: "30Mi"  # Лимит памяти
        ports:
          - containerPort: 3000
